### ISSUE TITLE
Things property is not set if the Forwarder is set as None.

### ISSUE THREAD

**Issue by tsathishkumar** [mozilla-iot/webthing-rust#2]
I tried to run the example of multiple-things and it seems that the properties set using the thread is not actually changing the property of sensor-thing (I was hitting the endpoint `/1/properties/level` and it was always 0).

I set the Forwarder of sensor in `make_sensor` function as follows and it is working fine.

```
thing.add_property(Box::new(BaseProperty::new(
        "level".to_owned(),
        json!(0),
        Some(Box::new(LevelValueForwarder)),
        Some(level_description),
    )))
```

Is it expected behaviour to not change properties if Forwarder is set as `None`?

**Comment by mrstegeman** [comment]
Yes, this is intended behavior. The sensor was intentionally set up as a read-only property, because it doesn't make much sense to be able to set a sensor's value externally. If you look at the light, though, you are able to set those properties.

**Comment by tsathishkumar** [comment]
In that case, I think creating a default Forwarder as part of the core crate would be useful, for those who don't want to perform any action on setting the value but just set the sensor's property. What do you think?

**Comment by mrstegeman** [comment]
That's a good idea. See #4

**Comment by tsathishkumar** [comment]
Seems like the EmptyValueForwarder got removed in commit c02c9f6e48e2a46efbae69493e9d1f954ee0e11b

Is it by mistake?

**Comment by tsathishkumar** [comment]
Seems like None will work now.

**Comment by mrstegeman** [comment]
Not by mistake. You can now use `None` instead, which is much more straightforward.
