### ISSUE TITLE
Problem with new ssl feature

### ISSUE THREAD

**Issue by mrpink76** [mozilla-iot/webthing-rust#34]
Thanks for the quick response regarding to my openssl issue :)

Tried using webthing-rust without specifying the "ssl" feature.

Seems like the dependency below and specifically the "alpn" feature (which is depricated according to Cargo.toml in actix-web) includes the openssl library:

```
actix-web = { version = "0.7", features=["alpn"] }
```

**Comment by mrstegeman** [comment]
Oops. Fixed in d4c4aba2a20af64cd18df7a39e28b867889c7493.
